iff.services.user-account.url=https://user-account:8444
iff.services.auth-server.url=https://auth-server:8445
iff.services.relationship.url=https://relationship:8446
iff.services.social-network.url=https://social-network:8447
