# Application messages
app.name = ${productName}
app.version = ${version}

# Spring Boot banner properties
spring.application.name = ${productName}
application.title = ${productName}
application.version = ${version}

# Tomcat server port
server.port = 9090
server.baseurl=http://localhost

# Log Levels
logging.level.web = WARN
logging.level.org.springframework = WARN
logging.level.io.netty = ERROR
logging.level.com.arc_e_tect.book.sedr.redthread = DEBUG

# Spring
spring.output.ansi.enabled = ALWAYS
management.endpoints.web.exposure.include=health, info

# Downstream service URLs
iff.services.user-account.url=https://localhost:9091
iff.services.auth-server.url=https://localhost:9092
iff.services.relationship.url=https://localhost:9093
iff.services.social-network.url=https://localhost:9094
