# Application messages
app.name = ${productName}
app.version = ${version}

# Spring Boot banner properties
spring.application.name = ${productName}
application.title = ${productName}
application.version = ${version}

# Tomcat server port
server.port = 9091
server.baseurl=http://localhost

# Log Levels
logging.level.web = WARN
logging.level.org.springframework = WARN
logging.level.io.netty = ERROR
logging.level.com.arc_e_tect.book.sedr.redthread = DEBUG

# Spring
spring.output.ansi.enabled = ALWAYS
management.endpoints.web.exposure.include=health, info
