response_field.username=The username of the newly created user account. This is the name provided by the user during account creation. This will be returned in the response to confirm successful account creation.

request_field.consent=Indicates whether the user has given consent to create an account.
request_field.username=Unique username for the user account. Must be alphanumeric and can include underscores, and must be at least 3 characters long, but no longer than 30 characters.
request_field.password=Password for the user account. Must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, one digit, and one special character.

path_parameter.username=The username for which the user account is being retrieved.

request_header.accept=Request header to specify the desired response format, typically JSON.
request_header.x_api_key=API key for authentication, required for accessing the user account management endpoints.

